/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
  api: [
    {
      type: 'category',
      collapsed: false,
      label: 'DID module',
      items: [
        { type: 'doc', id: 'api/modules/dids', label: 'Overview' },
        { type: 'doc', id: 'api/classes/dids.DID', label: 'DID class' },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'DID Session module',
      items: [
        { type: 'doc', id: 'api/modules/did_session', label: 'Overview' },
        { type: 'doc', id: 'api/classes/did_session.DIDSession', label: 'DIDSession class' },
      ],
    },
  ],
}

module.exports = sidebars
