name: Build docs
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build docs website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies and build
        run: pnpm install --frozen-lockfile

      - name: Build docs website
        run: (cd website && pnpm build)
